name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install modules
      run: yarn
    - name: Comment with test coverage relative to main
      uses: dkershner6/jest-coverage-commenter-action@v1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        test_command: "yarn test:coverage --changedSince=origin/main"
